### ISSUE TITLE
Sorting is broken in examples 

### ISSUE THREAD

**Issue by amandabee** [propublica/table-setter#16]
All three examples at the top of the [TableSetter overview page](http://propublica.github.com/table-setter/) link to stories where the sorting function is broken. A bit of investigation suggests that in each case, jquery.tablesorter.min.js can't be found.

**Comment by thejefflarson** [comment]
Oof, thanks for that I'll fix it tomorrow. In the meantime the example pages on github still work:

http://propublica.github.com/table-setter/documentation/tables/
