### ISSUE TITLE
Google docs

### ISSUE THREAD

**Issue by thejefflarson** [propublica/table-setter#17]
Google docs is throwing weird redirects for newly published documents. I suppose we'll need to use the api. If anyone has a solution send it along.

**Comment by palewire** [comment]
Is Google Docs the next rug they pull out?

**Comment by eyeseast** [comment]
Bloody hell, this is going to bite me, too. I'll keep an eye out for a fix.

**Comment by thejefflarson** [comment]
It's amazing trying to track down this issue with the support team now too.
Any insight would be awesome.

On Friday, December 30, 2011, Chris Amico <
reply@reply.github.com>
wrote:

**Comment by palewire** [comment]
I find that [the poets](http://www.youtube.com/watch?v=CzHLTy33qWM) provide the best insight into such large questions.
