### ISSUE TITLE
Sorting is reversed

### ISSUE THREAD

**Issue by ryanmark** [propublica/table-setter#4]
Specifying 'ascending' in the yaml config for a table results in descending order and visa versa. Clicking on a column head also applies the classes backwards. Arrow pointed down means descending and arrow pointing up means ascending. Like < and > but rotated 90º. I think.

**Comment by thejefflarson** [comment]
This is fixed in http://github.com/propublica/table-setter/commit/18d3b7b004682486afb1c777420c306fe9115ec8
