### ISSUE TITLE
in development / is unpredictable

### ISSUE THREAD

**Issue by kleinmatic** [propublica/table-setter#6]
I pushed a change that made trailing slashes optional, but when running this app in development the index path ('/') doesn't always seem to point to the index of open tables. In fact it pretty reliably just errors out now.

Mongrel doesn't work on my home Mac so I've been using 'shotgun -s thin config.ru' to run the app.

**Comment by thejefflarson** [comment]
Can you post a stacktrace of what happens when you go to the index path ?

**Comment by thejefflarson** [comment]
Fixed 0.2.2
