### ISSUE TITLE
application.js -- Overridden formatFloat breaks MSIE

### ISSUE THREAD

**Issue by JoeGermuska** [propublica/table-setter#7]
This block of code in 'application.js' throws an error in MSIE.  Commenting it out restored basic functionality.

  // Overriding format float to actually test a bit better.
  var oldFloat = $.tablesorter.formatFloat;
  $.tablesorter.formatFloat = $.tablesorter.formatInt = function(obj){
    return (obj === +obj) || (toString.call(obj) === '[object Number]') ? 0 : oldFloat(obj);
  };

**Comment by thejefflarson** [comment]
Thanks! Fixed with: 

https://github.com/propublica/table-setter/tree/c0eaf713407a63874cac3645acbc4c5a00be09fa

Might wanna reinstall the javascript. At some point we need to get rid of tablesorter.
